# Generated by Django 5.0.4 on 2026-03-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_url', models.URLField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(blank=True, max_length=60)),
                ('available_for_work', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
